apiVersion: apps/v1
kind: Deployment
metadata:
  name: slack-bot
  namespace: slack-bot
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: slack-bot
  template:
    metadata:
      labels:
        app.kubernetes.io/name: slack-bot
    spec:

      containers:
        - name: main
          image: python:latest
          command: ["python"]
          args: ["/app/main.py"]
          ports:
            - containerPort: 5000
              name: http
          volumeMounts:
            - name: slack-bot-script
              mountPath: "/app/main.py"
              subPath: "main.py"
      volumes:
        - name: slack-bot-script
          configMap:
            name: slack-bot
